export const types = {
    TOGGLE_LOADING: 'TOGGLE_LOADING',
    CLEAR_STORE: 'CLEAR_STORE',
    DUMMY_SAGA: 'DUMMY_SAGA',
    ADD_TO_SCHEDULE:'ADD_TO_SCHEDULE',
    ADD_TO_DO:'ADD_TO_DO',
    DELETE_SCHEDULE:'DELETE_SCHEDULE',
    EDIT_SCHEDULE:'EDIT_SCHEDULE',


}